# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Avaliação Gratuita(04aad890-7051-4edb-ba96-471cec51993b)'
    azureContainerRegistry: '{"loginServer":"containerregistermateus.azurecr.io", "id" : "/subscriptions/04aad890-7051-4edb-ba96-471cec51993b/resourceGroups/testeLaravel/providers/Microsoft.ContainerRegistry/registries/containerRegisterMateus"}'
    dockerComposeFile: '**/docker-compose.yml'
    projectName: 'containerregistermateus.azurecr.io/teste'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'
