version: '3'

networks:
  laravel:

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    image: containerregistermateus.azurecr.io/teste:latest
    ports:
      - "80:80"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel
